const { test } = require('node:test');
const assert = require('node:assert/strict');
const { mkdtempSync, rmSync } = require('node:fs');
const { tmpdir } = require('node:os');
const { join } = require('node:path');
const { CompetitionService } = require('./sessionService.cjs');
const { stations } = require('./stations.cjs');
function setup(t) { const dir = mkdtempSync(join(tmpdir(), 'competition-')); t.after(() => rmSync(dir, {recursive:true,force:true})); let now=100000; const service = new CompetitionService({dataDir:dir, now:()=>now}); const host=service.create({title:'Thi thử',hostName:'Thầy',durationMinutes:1,maxPlayers:10}); return {service,host,dir,advance:ms=>{now+=ms;service.tick();}}; }
function contestant(service,host,name='An') { return service.join(host.session.code,{nickname:name,outfitId:'student'}); }
function begin(service,host,player,advance) { service.ready(host.session.code,player.participantToken,true); service.start(host.session.code,host.hostToken); advance(5000); }
test('requires host authorization, all ready and five second countdown; rejects late entry', t=>{const {service,host,advance}=setup(t);const p=contestant(service,host);assert.throws(()=>service.start(host.session.code,'fake'));assert.throws(()=>service.start(host.session.code,host.hostToken));service.ready(host.session.code,p.participantToken,true);service.start(host.session.code,host.hostToken);assert.equal(service.snapshot(host.session.code).status,'countdown');advance(4999);assert.equal(service.snapshot(host.session.code).status,'countdown');advance(1);assert.equal(service.snapshot(host.session.code).status,'running');assert.throws(()=>contestant(service,host,'Late'));assert.equal(service.join(host.session.code,{participantToken:p.participantToken}).participantId,p.participantId);});
test('wrong retries cost only time, dedup unique answers, room checks, finish ranking', t=>{const {service,host,advance}=setup(t);const p=contestant(service,host);begin(service,host,p,advance);const qs=service.questions(host.session.code,host.hostToken);const q=qs[0];assert.throws(()=>service.answer(host.session.code,p.participantToken,{roomId:q.roomId,questionId:q.id,optionId:q.correctOptionId}));service.room(host.session.code,p.participantToken,q.roomId);service.position(host.session.code,p.participantToken,stations[q.id]);const wrong=service.answer(host.session.code,p.participantToken,{roomId:q.roomId,questionId:q.id,optionId:q.options.find(x=>x.id!==q.correctOptionId).id,requestId:'wrong'});assert.equal(wrong.correct,false);assert.equal(service.snapshot(host.session.code).participants[0].score,0);for(const x of qs){service.room(host.session.code,p.participantToken,x.roomId);service.position(host.session.code,p.participantToken,stations[x.id]);advance(10);const payload={roomId:x.roomId,questionId:x.id,optionId:x.correctOptionId};service.answer(host.session.code,p.participantToken,payload);if(x!==qs.at(-1))assert.equal(service.answer(host.session.code,p.participantToken,payload).duplicate,true);}const s=service.snapshot(host.session.code);assert.equal(s.status,'finalized');assert.equal(s.topThree[0].elapsedMs,100);assert.equal(s.topThree[0].score,10);assert.equal(s.topThree[0].wrongAttempts,1);assert.equal(s.topThree[0].attempts,11);});
test('private secrets omitted, recovery revokes former host, one active, restart aborts',t=>{const {service,host,dir}=setup(t);assert.throws(()=>service.create({}));const p=contestant(service,host);const encoded=JSON.stringify(service.snapshot(host.session.code));for(const secret of [p.participantToken,host.hostToken,host.recoveryCode,'correctOptionId','tokenHash'])assert.ok(!encoded.includes(secret));const recovery=service.recover(host.session.code,host.recoveryCode,'test');assert.throws(()=>service.questions(host.session.code,host.hostToken));assert.equal(service.questions(host.session.code,recovery.hostToken).length,10);const restarted=new CompetitionService({dataDir:dir});assert.equal(restarted.snapshot(host.session.code).status,'aborted');assert.equal(restarted.snapshot(host.session.code).topThree.length,0);});
test('timeout excludes unfinished players and disconnect never finalizes early',t=>{const {service,host,advance}=setup(t);const p=contestant(service,host);begin(service,host,p,advance);service.connected(host.session.code,p.participantToken,false);assert.equal(service.snapshot(host.session.code).status,'running');advance(60000);const s=service.snapshot(host.session.code);assert.equal(s.status,'finalized');assert.equal(s.participants[0].status,'timed_out');assert.deepEqual(s.topThree,[]);});

test('requires a contestant to walk within interaction distance before opening a room question', t=>{
  const {service,host,advance}=setup(t);const p=contestant(service,host);begin(service,host,p,advance);
  const first=service.questions(host.session.code,host.hostToken)[0];
  service.room(host.session.code,p.participantToken,first.roomId);
  assert.throws(()=>service.question(host.session.code,p.participantToken,first.roomId,first.id),/đi tới gần/i);
  service.position(host.session.code,p.participantToken,{x:-8,y:3,z:18});
  assert.equal(service.question(host.session.code,p.participantToken,first.roomId,first.id).id,first.id);
  service.position(host.session.code,p.participantToken,{x:10,y:3,z:18});
  assert.throws(()=>service.question(host.session.code,p.participantToken,first.roomId,first.id),/đi tới gần/i);
});
