const {randomBytes,randomUUID,createHash,timingSafeEqual}=require('node:crypto');
const path=require('node:path');
const {ResultStore}=require('./resultStore.cjs');
const bank=require('./questionBank.cjs');
const { stations, isAtStation } = require('./stations.cjs');
const hash=x=>createHash('sha256').update(String(x||'')).digest('hex');
const token=()=>randomBytes(32).toString('hex');
const same=(value,digest)=>typeof digest==='string' && timingSafeEqual(Buffer.from(hash(value)),Buffer.from(digest));
const active=s=>['lobby','countdown','running'].includes(s.status);
const safeText=(value,max)=>typeof value==='string'?value.trim().slice(0,max):'';
class CompetitionService {
 constructor({dataDir=process.env.COMPETITION_DATA_DIR||path.join(process.cwd(),'data','competition'),now=Date.now,onChange=()=>{}}={}) {this.now=now;this.onChange=onChange;this.store=new ResultStore(dataDir);this.sessions=new Map();this.recoveryAttempts=new Map();for(const s of this.store.load()){if(active(s)){s.status='aborted';s.endReason='server_restart';s.finalizedAt=this.now();}for(const p of s.participants)p.connected=false;this.sessions.set(s.code,s);this.store.save(s);}}
 get(code){const s=this.sessions.get(String(code||'').trim().toUpperCase());if(!s)throw Error('Không tìm thấy phiên thi.');return s;}
 save(s){this.store.save(s);this.onChange(s.code);}
 auth(s,credential){if(!same(credential,s.hostTokenHash))throw Error('Cần xác thực quyền chủ phòng.');}
 player(s,credential){const p=s.participants.find(x=>same(credential,x.tokenHash));if(!p)throw Error('Thông tin thí sinh không hợp lệ.');return p;}
 create(input){this.tick();if([...this.sessions.values()].some(active))throw Error('Đã có một cuộc thi đang hoạt động.');const title=safeText(input.title,100),hostName=safeText(input.hostName,50);const durationMinutes=Number(input.durationMinutes),maxPlayers=Number(input.maxPlayers);if(!title||!hostName||!Number.isInteger(durationMinutes)||durationMinutes<1||durationMinutes>180||!Number.isInteger(maxPlayers)||maxPlayers<1||maxPlayers>65)throw Error('Nhập tên phiên, chủ phòng, thời lượng 1–180 phút và 1–65 thí sinh.');let code;do{code=randomBytes(3).toString('hex').toUpperCase();}while(this.sessions.has(code));const hostToken=token(),recoveryCode=token();const s={id:randomUUID(),code,title,hostName,durationMinutes,maxPlayers,status:'lobby',createdAt:this.now(),startedAt:null,endsAt:null,finalizedAt:null,endReason:null,hostTokenHash:hash(hostToken),recoveryHash:hash(recoveryCode),questionBankVersion:bank.version,questions:structuredClone(bank.questions),participants:[],audit:[{action:'created',at:this.now()}]};this.sessions.set(code,s);this.save(s);return {session:this.snapshot(code),hostToken,recoveryCode};}
 recover(code,recoveryCode,ip='unknown'){const key=String(ip);const old=this.recoveryAttempts.get(key);const record=old&&old.until>this.now()?old:{count:0,until:this.now()+60000};this.recoveryAttempts.set(key,record);if(++record.count>5)throw Error('Thử quá nhiều lần. Hãy chờ một phút.');const s=this.get(code);if(!same(recoveryCode,s.recoveryHash))throw Error('Mã khôi phục không hợp lệ.');const hostToken=token();s.hostTokenHash=hash(hostToken);s.audit.push({action:'host_recovered',at:this.now()});this.save(s);return {session:this.snapshot(code),hostToken};}
 join(code,input){this.tick();const s=this.get(code);if(input.participantToken){const p=this.player(s,input.participantToken);p.connected=true;this.save(s);return {session:this.snapshot(code),participantId:p.id,participantToken:input.participantToken};}if(s.status!=='lobby')throw Error('Danh sách thi đã chốt. Bạn có thể xem bảng công khai.');if(s.participants.length>=s.maxPlayers)throw Error('Phiên thi đã đủ người.');const nickname=safeText(input.nickname,40);if(!nickname)throw Error('Vui lòng nhập tên.');const participantToken=token();const p={id:randomUUID(),nickname,outfitId:['student','baba','aodai','casual'].includes(input.outfitId)?input.outfitId:'student',tokenHash:hash(participantToken),ready:false,connected:true,currentRoomId:'lobby',status:'waiting',correctQuestionIds:[],attempts:0,wrongAttempts:0,finishedAt:null,elapsedMs:null,answers:[],requests:{}};s.participants.push(p);this.save(s);return {session:this.snapshot(code),participantId:p.id,participantToken};}
 ready(code,credential,ready){const s=this.get(code),p=this.player(s,credential);if(s.status!=='lobby')throw Error('Phiên thi đã bắt đầu.');p.ready=ready===true;this.save(s);}
 start(code,credential){this.tick();const s=this.get(code);this.auth(s,credential);if(s.status!=='lobby'||!s.participants.length||s.participants.some(p=>!p.ready||!p.connected))throw Error('Cần tất cả thí sinh kết nối và sẵn sàng.');if(bank.ROOMS.some(r=>s.questions.filter(q=>q.roomId===r).length!==2)||new Set(s.questions.map(q=>q.id)).size!==10)throw Error('Bộ câu hỏi không hợp lệ.');s.status='countdown';s.startedAt=this.now()+5000;s.endsAt=s.startedAt+s.durationMinutes*60000;for(const p of s.participants)p.status='racing';s.audit.push({action:'started',at:this.now()});this.save(s);}
 room(code,credential,roomId){const s=this.get(code),p=this.player(s,credential);if(![...bank.ROOMS,'lobby'].includes(roomId))throw Error('Phòng không hợp lệ.');p.currentRoomId=roomId;this.save(s);}
 position(code,credential,position){const s=this.get(code),p=this.player(s,credential);const x=Number(position?.x),z=Number(position?.z);if(!Number.isFinite(x)||!Number.isFinite(z)||Math.abs(x)>40||z<-20||z>280)throw Error('Vị trí không hợp lệ.');p.position={x,z,at:this.now()};}
 question(code,credential,roomId,questionId){const s=this.get(code),p=this.player(s,credential);const q=s.questions.find(item=>item.id===questionId);if(!q||q.roomId!==roomId||p.currentRoomId!==roomId)throw Error('Câu hỏi không thuộc phòng hiện tại.');if(!stations[q.id]||!isAtStation(q.id,p.position))throw Error('Hãy đi tới gần điểm tương tác rồi nhấp vào tranh để mở câu hỏi.');return {id:q.id,roomId:q.roomId,prompt:q.prompt,options:structuredClone(q.options)};}
 answer(code,credential,input){this.tick();const s=this.get(code),p=this.player(s,credential);if(s.status!=='running'||p.status!=='racing')throw Error('Hiện không thể nộp câu trả lời.');const q=s.questions.find(q=>q.id===input.questionId);if(!q||q.roomId!==input.roomId||p.currentRoomId!==q.roomId)throw Error('Câu hỏi không thuộc phòng hiện tại.');if(!isAtStation(q.id,p.position))throw Error('Hãy đứng gần tranh đang mở để trả lời.');if(!q.options.some(o=>o.id===input.optionId))throw Error('Lựa chọn không hợp lệ.');const requestId=typeof input.requestId==='string'?input.requestId.slice(0,80):null;if(requestId&&Object.hasOwn(p.requests,requestId))return {...p.requests[requestId],duplicate:true};if(p.correctQuestionIds.includes(q.id))return {correct:true,duplicate:true};if(p.attempts>=10000)throw Error('Vượt giới hạn lượt nộp của phiên.');const correct=input.optionId===q.correctOptionId;p.attempts++;if(correct)p.correctQuestionIds.push(q.id);else p.wrongAttempts++;p.answers.push({questionId:q.id,optionId:input.optionId,correct,at:this.now()});const result={correct,duplicate:false};if(requestId)Object.defineProperty(p.requests,requestId,{value:result,enumerable:true,writable:true,configurable:true});if(p.correctQuestionIds.length===10){p.status='finished';p.finishedAt=this.now();p.elapsedMs=p.finishedAt-s.startedAt;}if(s.participants.every(p=>['finished','withdrawn'].includes(p.status)))this.finalize(s,'all_finished');else this.save(s);return result;}
 connected(code,credential,value){const s=this.get(code),p=this.player(s,credential);p.connected=value;this.save(s);}
 withdraw(code,credential,id,reason){this.tick();const s=this.get(code);this.auth(s,credential);if(!active(s))throw Error('Phiên đã đóng.');const p=s.participants.find(x=>x.id===id);if(!p)throw Error('Không tìm thấy thí sinh.');if(s.status==='lobby')s.participants=s.participants.filter(x=>x!==p);else {if(p.status==='finished')throw Error('Không thể rút kết quả đã hoàn thành.');p.status='withdrawn';}s.audit.push({action:'withdrawn',participantId:id,reason:safeText(reason,200),at:this.now()});if(s.status!=='lobby'&&s.participants.every(p=>['finished','withdrawn'].includes(p.status)))this.finalize(s,'withdrawal');else this.save(s);}
 end(code,credential,reason){this.tick();const s=this.get(code);this.auth(s,credential);if(!active(s))throw Error('Phiên đã đóng.');s.audit.push({action:'host_ended',reason:safeText(reason,200),at:this.now()});this.finalize(s,'host_ended');}
 finalize(s,reason){if(!active(s))return;s.status='finalized';s.finalizedAt=this.now();s.endReason=reason;for(const p of s.participants)if(['racing','waiting'].includes(p.status))p.status='timed_out';this.save(s);}
 tick(){for(const s of this.sessions.values()){if(s.status==='countdown'&&this.now()>=s.startedAt){s.status='running';this.save(s);}if(s.status==='running'&&this.now()>=s.endsAt)this.finalize(s,'timeout');}for(const [key,value] of this.recoveryAttempts)if(value.until<=this.now())this.recoveryAttempts.delete(key);}
 questions(code,credential){const s=this.get(code);this.auth(s,credential);return structuredClone(s.questions);}
 snapshot(code){const s=this.get(code);const participants=s.participants.map(p=>({id:p.id,nickname:p.nickname,outfitId:p.outfitId,ready:p.ready,connected:p.connected,currentRoomId:p.currentRoomId,status:p.status,correctQuestionIds:[...p.correctQuestionIds],progress:Object.fromEntries(bank.ROOMS.map(r=>[r,s.questions.filter(q=>q.roomId===r&&p.correctQuestionIds.includes(q.id)).length])),score:p.correctQuestionIds.length,attempts:p.attempts,wrongAttempts:p.wrongAttempts,finishedAt:p.finishedAt,elapsedMs:p.elapsedMs,rank:null}));const ranking=participants.filter(p=>p.status==='finished').sort((a,b)=>a.elapsedMs-b.elapsedMs||a.id.localeCompare(b.id));ranking.forEach((p,i)=>{p.rank=i&&p.elapsedMs===ranking[i-1].elapsedMs?ranking[i-1].rank:i+1;});return {id:s.id,code:s.code,title:s.title,hostName:s.hostName,status:s.status,durationMinutes:s.durationMinutes,maxPlayers:s.maxPlayers,createdAt:s.createdAt,startedAt:s.startedAt,endsAt:s.endsAt,finalizedAt:s.finalizedAt,endReason:s.endReason,serverNow:this.now(),questionBankVersion:s.questionBankVersion,questions:s.questions.map(({id,roomId,prompt,options})=>({id,roomId,prompt,options:structuredClone(options)})),participants,ranking,topThree:s.status==='finalized'?ranking.filter(p=>p.rank<=3):[]};}
}
module.exports={CompetitionService};
