version: '3.8'

services:
  ws-server:
    build:
      context: .
      dockerfile: Dockerfile.ws
    ports:
      - "3001:3001"
    environment:
      - WS_PORT=3001
    restart: always

  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WS_URL=http://localhost:3001  # Thay đổi thành IP/Domain thật của máy chủ khi deploy
      - PORT=3000
    depends_on:
      - ws-server
    restart: always
